# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26dd65bacfdf977446067cb5b8a20a121f0adbdd5412fcf62b9a1c851c3562c273be76b996be2e987debe621d83610838106b2e3eecf6de6b209c34c4ffba651

test:
  secret_key_base: cc4f11870a11caf19137400047139a2df5e4d23a9a9210ed2b303c1801bcb386d9c1d4a7e6bab2b357dd2fc17f10646af16837e8e65cb393748915a7a9657df9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
